### ISSUE TITLE
Running the contributed command:'extension.resolveMissingImportsForHighlighted' failed.

### ISSUE THREAD

**Issue by daslicht** [Sammons/ts-import-assistance#8] opened 2016-07-10 11:22 UTC
When I call cmd + shift + p, then type "Resolve and import symbol". 

I get : 

```
Running the contributed command:'extension.resolveMissingImportsForHighlighted' failed.
```

?

**Comment by Sammons** [comment] 2016-07-11 01:18
@daslicht that happens when it throws an uncaught error, can you tell me what text you had highlighted, and where the symbol was in the file system related to the current document? 

If you're up to it, you can debug the extension by cloning this repo and running it in debug mode. it will start a second instance of code that you can use to open and replicate the error.

I'll take a scan over the code and see if I can find it anyways.

Thanks!

**Comment by daslicht** [comment] 2016-07-11 10:25
I can't remember :)next time I will write it down :)

**Comment by Sammons** [comment] 2016-08-17 06:02
Closing for now since I can't reproduce, let me know if it comes back! Thanks!

**Closed as completed by Sammons** 2016-08-17 06:02 UTC
Labels: bug, needs more information to reproduce
